import '../styles/global.scss';
import { Inter } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';
import { getServerSession } from 'next-auth/next';
import { authOptions } from './lib/auth';
import { cookies } from 'next/headers';
import Providers from './Provider';
import Layout from '@/components/Layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = cookies().get('session');
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
